export const enum IpcEvents {
    FT_GET_FIC_CONTENT = 'FT_GET_FIC_CONTENT',
    FT_GET_FFNET_FIC_CONTENT = 'FT_GET_FFNET_FIC_CONTENT',
    FT_CAPTCHA = 'FT_CAPTCHA',
    FT_CAPTCHA_SOLVED = 'FT_CAPTCHA_SOLVED'
}