export const enum IpcEvents {
    FT_GET_FIC_CONTENT = 'FT_GET_FIC_CONTENT',
    FT_GET_FFNET_FIC_CONTENT = 'FT_GET_FFNET_FIC_CONTENT',

    FT_CAPTCHA_SOLVED = 'FT_CAPTCHA_SOLVED',
    FT_CAPTCHA_SHOW_WINDOW = 'FT_CAPTCHA_SHOW_WINDOW',
}