export const enum IpcEvents {
    GET_AO3_FIC_CONTENT = 'GET_AO3_FIC_CONTENT',
    GET_AO3_FIC_METADATA = 'GET_AO3_FIC_METADATA',

    GET_FFNET_FIC_CONTENT = 'GET_FFNET_FIC_CONTENT',

    CAPTCHA_SOLVED = 'CAPTCHA_SOLVED',
    CAPTCHA_SHOW_WINDOW = 'CAPTCHA_SHOW_WINDOW',
}